Uppates page and section titles
localgovdrupal/localgov_elections pull request #71
Opened 2024-06-28 13:52 UTC by markconroy

Closes #63

2024-07-01 13:41 UTC, chriswales95 requested changes
Hi @markconroy, seems good but one issue I think we need to address!

2024-07-01 13:41 UTC, chriswales95 commented on localgov_elections.module
>  /**
This throws an error on view pages clicked from the menu block. $node is not always an entity it is sometimes a string.

2024-07-01 13:45 UTC, chriswales95 commented on localgov_elections.module
>  /**
Well, at least on my version of Drupal. This fixed it locally for me:

```
if (!$node){
    return;
  }
  if (!($node instanceof NodeInterface)){
    $node = Node::load($node);
  }
```

2024-07-02 09:22 UTC, finnlewis commented
@chriswales95 are you happy with this one now?

2024-07-02 10:57 UTC, chriswales95 approved these changes
Looks good to me now. No errors.

2024-07-02 11:22 UTC, merged